// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"fmt"
)

type BaseRequest struct {
	Id         *int64 `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	IsDelete   *int32 `thrift:"isDelete,2,optional" frugal:"2,optional,i32" json:"isDelete,omitempty"`
	CreatedBy  *int64 `thrift:"createdBy,3,optional" frugal:"3,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy  *int64 `thrift:"updatedBy,4,optional" frugal:"4,optional,i64" json:"updatedBy,omitempty"`
	CreateTime *int64 `thrift:"createTime,5,optional" frugal:"5,optional,i64" json:"createTime,omitempty"`
	UpdateTime *int64 `thrift:"updateTime,6,optional" frugal:"6,optional,i64" json:"updateTime,omitempty"`
}

func NewBaseRequest() *BaseRequest {
	return &BaseRequest{}
}

func (p *BaseRequest) InitDefault() {
}

var BaseRequest_Id_DEFAULT int64

func (p *BaseRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return BaseRequest_Id_DEFAULT
	}
	return *p.Id
}

var BaseRequest_IsDelete_DEFAULT int32

func (p *BaseRequest) GetIsDelete() (v int32) {
	if !p.IsSetIsDelete() {
		return BaseRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var BaseRequest_CreatedBy_DEFAULT int64

func (p *BaseRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return BaseRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var BaseRequest_UpdatedBy_DEFAULT int64

func (p *BaseRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return BaseRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var BaseRequest_CreateTime_DEFAULT int64

func (p *BaseRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return BaseRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var BaseRequest_UpdateTime_DEFAULT int64

func (p *BaseRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return BaseRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *BaseRequest) SetId(val *int64) {
	p.Id = val
}
func (p *BaseRequest) SetIsDelete(val *int32) {
	p.IsDelete = val
}
func (p *BaseRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *BaseRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *BaseRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *BaseRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}

func (p *BaseRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *BaseRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *BaseRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *BaseRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *BaseRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *BaseRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *BaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseRequest(%+v)", *p)
}

var fieldIDToName_BaseRequest = map[int16]string{
	1: "id",
	2: "isDelete",
	3: "createdBy",
	4: "updatedBy",
	5: "createTime",
	6: "updateTime",
}

type BaseResponse struct {
	Id         int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	IsDelete   int32 `thrift:"isDelete,2" frugal:"2,default,i32" json:"isDelete"`
	CreatedBy  int64 `thrift:"createdBy,3" frugal:"3,default,i64" json:"createdBy"`
	UpdatedBy  int64 `thrift:"updatedBy,4" frugal:"4,default,i64" json:"updatedBy"`
	CreateTime int64 `thrift:"createTime,5" frugal:"5,default,i64" json:"createTime"`
	UpdateTime int64 `thrift:"updateTime,6" frugal:"6,default,i64" json:"updateTime"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetId() (v int64) {
	return p.Id
}

func (p *BaseResponse) GetIsDelete() (v int32) {
	return p.IsDelete
}

func (p *BaseResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *BaseResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *BaseResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *BaseResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *BaseResponse) SetId(val int64) {
	p.Id = val
}
func (p *BaseResponse) SetIsDelete(val int32) {
	p.IsDelete = val
}
func (p *BaseResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *BaseResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *BaseResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *BaseResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "id",
	2: "isDelete",
	3: "createdBy",
	4: "updatedBy",
	5: "createTime",
	6: "updateTime",
}
