// Code generated by Kitex v0.16.3. DO NOT EDIT.

package userheaderservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "github.com/kouleen/user-center/kitex_gen/user"
	user_position "github.com/kouleen/user-center/kitex_gen/user_position"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error)
	SendSmsMessage(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r bool, err error)
	Logout(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r bool, err error)
	QueryUserHeaderPage(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r *user.UserHeaderPageResponse, err error)
	QueryUserHeaderList(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r []*user.UserHeaderResponse, err error)
	QueryUserHeaderInfo(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r *user.UserHeaderResponse, err error)
	QueryUserPositionPage(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r *user_position.UserPositionPageResponse, err error)
	SaveUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error)
	UpdateUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error)
	DeleteUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserHeaderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserHeaderServiceClient struct {
	*kClient
}

func (p *kUserHeaderServiceClient) Login(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, loginRequest)
}

func (p *kUserHeaderServiceClient) SendSmsMessage(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSmsMessage(ctx, loginRequest)
}

func (p *kUserHeaderServiceClient) Logout(ctx context.Context, loginRequest *user.LoginRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, loginRequest)
}

func (p *kUserHeaderServiceClient) QueryUserHeaderPage(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r *user.UserHeaderPageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserHeaderPage(ctx, userHeaderRequest)
}

func (p *kUserHeaderServiceClient) QueryUserHeaderList(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r []*user.UserHeaderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserHeaderList(ctx, userHeaderRequest)
}

func (p *kUserHeaderServiceClient) QueryUserHeaderInfo(ctx context.Context, userHeaderRequest *user.UserHeaderRequest, callOptions ...callopt.Option) (r *user.UserHeaderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserHeaderInfo(ctx, userHeaderRequest)
}

func (p *kUserHeaderServiceClient) QueryUserPositionPage(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r *user_position.UserPositionPageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserPositionPage(ctx, userPositionRequest)
}

func (p *kUserHeaderServiceClient) SaveUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveUserPosition(ctx, userPositionRequest)
}

func (p *kUserHeaderServiceClient) UpdateUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserPosition(ctx, userPositionRequest)
}

func (p *kUserHeaderServiceClient) DeleteUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserPosition(ctx, userPositionRequest)
}
