// Code generated by Kitex v0.16.3. DO NOT EDIT.

package userheaderservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "github.com/kouleen/user-center/kitex_gen/user"
	user_position "github.com/kouleen/user-center/kitex_gen/user_position"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserHeaderServiceLoginArgs,
		newUserHeaderServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendSmsMessage": kitex.NewMethodInfo(
		sendSmsMessageHandler,
		newUserHeaderServiceSendSmsMessageArgs,
		newUserHeaderServiceSendSmsMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserHeaderServiceLogoutArgs,
		newUserHeaderServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderPage": kitex.NewMethodInfo(
		queryUserHeaderPageHandler,
		newUserHeaderServiceQueryUserHeaderPageArgs,
		newUserHeaderServiceQueryUserHeaderPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderList": kitex.NewMethodInfo(
		queryUserHeaderListHandler,
		newUserHeaderServiceQueryUserHeaderListArgs,
		newUserHeaderServiceQueryUserHeaderListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderInfo": kitex.NewMethodInfo(
		queryUserHeaderInfoHandler,
		newUserHeaderServiceQueryUserHeaderInfoArgs,
		newUserHeaderServiceQueryUserHeaderInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserPositionPage": kitex.NewMethodInfo(
		queryUserPositionPageHandler,
		newUserHeaderServiceQueryUserPositionPageArgs,
		newUserHeaderServiceQueryUserPositionPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveUserPosition": kitex.NewMethodInfo(
		saveUserPositionHandler,
		newUserHeaderServiceSaveUserPositionArgs,
		newUserHeaderServiceSaveUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserPosition": kitex.NewMethodInfo(
		updateUserPositionHandler,
		newUserHeaderServiceUpdateUserPositionArgs,
		newUserHeaderServiceUpdateUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserPosition": kitex.NewMethodInfo(
		deleteUserPositionHandler,
		newUserHeaderServiceDeleteUserPositionArgs,
		newUserHeaderServiceDeleteUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userHeaderServiceServiceInfo                = NewServiceInfo()
	userHeaderServiceServiceInfoForClient       = NewServiceInfoForClient()
	userHeaderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userHeaderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userHeaderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userHeaderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserHeaderService"
	handlerType := (*user.UserHeaderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceLoginArgs)
	realResult := result.(*user.UserHeaderServiceLoginResult)
	success, err := handler.(user.UserHeaderService).Login(ctx, realArg.LoginRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserHeaderServiceLoginArgs() interface{} {
	return user.NewUserHeaderServiceLoginArgs()
}

func newUserHeaderServiceLoginResult() interface{} {
	return user.NewUserHeaderServiceLoginResult()
}

func sendSmsMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceSendSmsMessageArgs)
	realResult := result.(*user.UserHeaderServiceSendSmsMessageResult)
	success, err := handler.(user.UserHeaderService).SendSmsMessage(ctx, realArg.LoginRequest)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserHeaderServiceSendSmsMessageArgs() interface{} {
	return user.NewUserHeaderServiceSendSmsMessageArgs()
}

func newUserHeaderServiceSendSmsMessageResult() interface{} {
	return user.NewUserHeaderServiceSendSmsMessageResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceLogoutArgs)
	realResult := result.(*user.UserHeaderServiceLogoutResult)
	success, err := handler.(user.UserHeaderService).Logout(ctx, realArg.LoginRequest)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserHeaderServiceLogoutArgs() interface{} {
	return user.NewUserHeaderServiceLogoutArgs()
}

func newUserHeaderServiceLogoutResult() interface{} {
	return user.NewUserHeaderServiceLogoutResult()
}

func queryUserHeaderPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceQueryUserHeaderPageArgs)
	realResult := result.(*user.UserHeaderServiceQueryUserHeaderPageResult)
	success, err := handler.(user.UserHeaderService).QueryUserHeaderPage(ctx, realArg.UserHeaderRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserHeaderServiceQueryUserHeaderPageArgs() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderPageArgs()
}

func newUserHeaderServiceQueryUserHeaderPageResult() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderPageResult()
}

func queryUserHeaderListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceQueryUserHeaderListArgs)
	realResult := result.(*user.UserHeaderServiceQueryUserHeaderListResult)
	success, err := handler.(user.UserHeaderService).QueryUserHeaderList(ctx, realArg.UserHeaderRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserHeaderServiceQueryUserHeaderListArgs() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderListArgs()
}

func newUserHeaderServiceQueryUserHeaderListResult() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderListResult()
}

func queryUserHeaderInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceQueryUserHeaderInfoArgs)
	realResult := result.(*user.UserHeaderServiceQueryUserHeaderInfoResult)
	success, err := handler.(user.UserHeaderService).QueryUserHeaderInfo(ctx, realArg.UserHeaderRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserHeaderServiceQueryUserHeaderInfoArgs() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderInfoArgs()
}

func newUserHeaderServiceQueryUserHeaderInfoResult() interface{} {
	return user.NewUserHeaderServiceQueryUserHeaderInfoResult()
}

func queryUserPositionPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceQueryUserPositionPageArgs)
	realResult := result.(*user.UserHeaderServiceQueryUserPositionPageResult)
	success, err := handler.(user.UserHeaderService).QueryUserPositionPage(ctx, realArg.UserPositionRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserHeaderServiceQueryUserPositionPageArgs() interface{} {
	return user.NewUserHeaderServiceQueryUserPositionPageArgs()
}

func newUserHeaderServiceQueryUserPositionPageResult() interface{} {
	return user.NewUserHeaderServiceQueryUserPositionPageResult()
}

func saveUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceSaveUserPositionArgs)
	realResult := result.(*user.UserHeaderServiceSaveUserPositionResult)
	success, err := handler.(user.UserHeaderService).SaveUserPosition(ctx, realArg.UserPositionRequest)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserHeaderServiceSaveUserPositionArgs() interface{} {
	return user.NewUserHeaderServiceSaveUserPositionArgs()
}

func newUserHeaderServiceSaveUserPositionResult() interface{} {
	return user.NewUserHeaderServiceSaveUserPositionResult()
}

func updateUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceUpdateUserPositionArgs)
	realResult := result.(*user.UserHeaderServiceUpdateUserPositionResult)
	success, err := handler.(user.UserHeaderService).UpdateUserPosition(ctx, realArg.UserPositionRequest)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserHeaderServiceUpdateUserPositionArgs() interface{} {
	return user.NewUserHeaderServiceUpdateUserPositionArgs()
}

func newUserHeaderServiceUpdateUserPositionResult() interface{} {
	return user.NewUserHeaderServiceUpdateUserPositionResult()
}

func deleteUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserHeaderServiceDeleteUserPositionArgs)
	realResult := result.(*user.UserHeaderServiceDeleteUserPositionResult)
	success, err := handler.(user.UserHeaderService).DeleteUserPosition(ctx, realArg.UserPositionRequest)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserHeaderServiceDeleteUserPositionArgs() interface{} {
	return user.NewUserHeaderServiceDeleteUserPositionArgs()
}

func newUserHeaderServiceDeleteUserPositionResult() interface{} {
	return user.NewUserHeaderServiceDeleteUserPositionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Login(ctx context.Context, loginRequest *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args user.UserHeaderServiceLoginArgs
	_args.LoginRequest = loginRequest
	var _result user.UserHeaderServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendSmsMessage(ctx context.Context, loginRequest *user.LoginRequest) (r bool, err error) {
	var _args user.UserHeaderServiceSendSmsMessageArgs
	_args.LoginRequest = loginRequest
	var _result user.UserHeaderServiceSendSmsMessageResult
	if err = p.c.Call(ctx, "SendSmsMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, loginRequest *user.LoginRequest) (r bool, err error) {
	var _args user.UserHeaderServiceLogoutArgs
	_args.LoginRequest = loginRequest
	var _result user.UserHeaderServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderPage(ctx context.Context, userHeaderRequest *user.UserHeaderRequest) (r *user.UserHeaderPageResponse, err error) {
	var _args user.UserHeaderServiceQueryUserHeaderPageArgs
	_args.UserHeaderRequest = userHeaderRequest
	var _result user.UserHeaderServiceQueryUserHeaderPageResult
	if err = p.c.Call(ctx, "QueryUserHeaderPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderList(ctx context.Context, userHeaderRequest *user.UserHeaderRequest) (r []*user.UserHeaderResponse, err error) {
	var _args user.UserHeaderServiceQueryUserHeaderListArgs
	_args.UserHeaderRequest = userHeaderRequest
	var _result user.UserHeaderServiceQueryUserHeaderListResult
	if err = p.c.Call(ctx, "QueryUserHeaderList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderInfo(ctx context.Context, userHeaderRequest *user.UserHeaderRequest) (r *user.UserHeaderResponse, err error) {
	var _args user.UserHeaderServiceQueryUserHeaderInfoArgs
	_args.UserHeaderRequest = userHeaderRequest
	var _result user.UserHeaderServiceQueryUserHeaderInfoResult
	if err = p.c.Call(ctx, "QueryUserHeaderInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserPositionPage(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r *user_position.UserPositionPageResponse, err error) {
	var _args user.UserHeaderServiceQueryUserPositionPageArgs
	_args.UserPositionRequest = userPositionRequest
	var _result user.UserHeaderServiceQueryUserPositionPageResult
	if err = p.c.Call(ctx, "QueryUserPositionPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserHeaderServiceSaveUserPositionArgs
	_args.UserPositionRequest = userPositionRequest
	var _result user.UserHeaderServiceSaveUserPositionResult
	if err = p.c.Call(ctx, "SaveUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserHeaderServiceUpdateUserPositionArgs
	_args.UserPositionRequest = userPositionRequest
	var _result user.UserHeaderServiceUpdateUserPositionResult
	if err = p.c.Call(ctx, "UpdateUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserHeaderServiceDeleteUserPositionArgs
	_args.UserPositionRequest = userPositionRequest
	var _result user.UserHeaderServiceDeleteUserPositionResult
	if err = p.c.Call(ctx, "DeleteUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
