// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"github.com/kouleen/user-center/kitex_gen/user_position"
)

type UserHeaderService interface {
	Login(ctx context.Context, loginRequest *LoginRequest) (r *LoginResponse, err error)

	SendSmsMessage(ctx context.Context, loginRequest *LoginRequest) (r bool, err error)

	Logout(ctx context.Context, loginRequest *LoginRequest) (r bool, err error)

	QueryUserHeaderPage(ctx context.Context, userHeaderRequest *UserHeaderRequest) (r *UserHeaderPageResponse, err error)

	QueryUserHeaderList(ctx context.Context, userHeaderRequest *UserHeaderRequest) (r []*UserHeaderResponse, err error)

	QueryUserHeaderInfo(ctx context.Context, userHeaderRequest *UserHeaderRequest) (r *UserHeaderResponse, err error)

	QueryUserPositionPage(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r *user_position.UserPositionPageResponse, err error)

	SaveUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error)

	UpdateUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error)

	DeleteUserPosition(ctx context.Context, userPositionRequest *user_position.UserPositionRequest) (r bool, err error)
}

type UserHeaderServiceLoginArgs struct {
	LoginRequest *LoginRequest `thrift:"loginRequest,1" frugal:"1,default,LoginRequest" json:"loginRequest"`
}

func NewUserHeaderServiceLoginArgs() *UserHeaderServiceLoginArgs {
	return &UserHeaderServiceLoginArgs{}
}

func (p *UserHeaderServiceLoginArgs) InitDefault() {
}

var UserHeaderServiceLoginArgs_LoginRequest_DEFAULT *LoginRequest

func (p *UserHeaderServiceLoginArgs) GetLoginRequest() (v *LoginRequest) {
	if !p.IsSetLoginRequest() {
		return UserHeaderServiceLoginArgs_LoginRequest_DEFAULT
	}
	return p.LoginRequest
}
func (p *UserHeaderServiceLoginArgs) SetLoginRequest(val *LoginRequest) {
	p.LoginRequest = val
}

func (p *UserHeaderServiceLoginArgs) IsSetLoginRequest() bool {
	return p.LoginRequest != nil
}

func (p *UserHeaderServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceLoginArgs = map[int16]string{
	1: "loginRequest",
}

type UserHeaderServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserHeaderServiceLoginResult() *UserHeaderServiceLoginResult {
	return &UserHeaderServiceLoginResult{}
}

func (p *UserHeaderServiceLoginResult) InitDefault() {
}

var UserHeaderServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserHeaderServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserHeaderServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserHeaderServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceLoginResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceSendSmsMessageArgs struct {
	LoginRequest *LoginRequest `thrift:"loginRequest,1" frugal:"1,default,LoginRequest" json:"loginRequest"`
}

func NewUserHeaderServiceSendSmsMessageArgs() *UserHeaderServiceSendSmsMessageArgs {
	return &UserHeaderServiceSendSmsMessageArgs{}
}

func (p *UserHeaderServiceSendSmsMessageArgs) InitDefault() {
}

var UserHeaderServiceSendSmsMessageArgs_LoginRequest_DEFAULT *LoginRequest

func (p *UserHeaderServiceSendSmsMessageArgs) GetLoginRequest() (v *LoginRequest) {
	if !p.IsSetLoginRequest() {
		return UserHeaderServiceSendSmsMessageArgs_LoginRequest_DEFAULT
	}
	return p.LoginRequest
}
func (p *UserHeaderServiceSendSmsMessageArgs) SetLoginRequest(val *LoginRequest) {
	p.LoginRequest = val
}

func (p *UserHeaderServiceSendSmsMessageArgs) IsSetLoginRequest() bool {
	return p.LoginRequest != nil
}

func (p *UserHeaderServiceSendSmsMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceSendSmsMessageArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceSendSmsMessageArgs = map[int16]string{
	1: "loginRequest",
}

type UserHeaderServiceSendSmsMessageResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserHeaderServiceSendSmsMessageResult() *UserHeaderServiceSendSmsMessageResult {
	return &UserHeaderServiceSendSmsMessageResult{}
}

func (p *UserHeaderServiceSendSmsMessageResult) InitDefault() {
}

var UserHeaderServiceSendSmsMessageResult_Success_DEFAULT bool

func (p *UserHeaderServiceSendSmsMessageResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceSendSmsMessageResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserHeaderServiceSendSmsMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserHeaderServiceSendSmsMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceSendSmsMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceSendSmsMessageResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceSendSmsMessageResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceLogoutArgs struct {
	LoginRequest *LoginRequest `thrift:"loginRequest,1" frugal:"1,default,LoginRequest" json:"loginRequest"`
}

func NewUserHeaderServiceLogoutArgs() *UserHeaderServiceLogoutArgs {
	return &UserHeaderServiceLogoutArgs{}
}

func (p *UserHeaderServiceLogoutArgs) InitDefault() {
}

var UserHeaderServiceLogoutArgs_LoginRequest_DEFAULT *LoginRequest

func (p *UserHeaderServiceLogoutArgs) GetLoginRequest() (v *LoginRequest) {
	if !p.IsSetLoginRequest() {
		return UserHeaderServiceLogoutArgs_LoginRequest_DEFAULT
	}
	return p.LoginRequest
}
func (p *UserHeaderServiceLogoutArgs) SetLoginRequest(val *LoginRequest) {
	p.LoginRequest = val
}

func (p *UserHeaderServiceLogoutArgs) IsSetLoginRequest() bool {
	return p.LoginRequest != nil
}

func (p *UserHeaderServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceLogoutArgs = map[int16]string{
	1: "loginRequest",
}

type UserHeaderServiceLogoutResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserHeaderServiceLogoutResult() *UserHeaderServiceLogoutResult {
	return &UserHeaderServiceLogoutResult{}
}

func (p *UserHeaderServiceLogoutResult) InitDefault() {
}

var UserHeaderServiceLogoutResult_Success_DEFAULT bool

func (p *UserHeaderServiceLogoutResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceLogoutResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserHeaderServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserHeaderServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceLogoutResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceQueryUserHeaderPageArgs struct {
	UserHeaderRequest *UserHeaderRequest `thrift:"userHeaderRequest,1" frugal:"1,default,UserHeaderRequest" json:"userHeaderRequest"`
}

func NewUserHeaderServiceQueryUserHeaderPageArgs() *UserHeaderServiceQueryUserHeaderPageArgs {
	return &UserHeaderServiceQueryUserHeaderPageArgs{}
}

func (p *UserHeaderServiceQueryUserHeaderPageArgs) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderPageArgs_UserHeaderRequest_DEFAULT *UserHeaderRequest

func (p *UserHeaderServiceQueryUserHeaderPageArgs) GetUserHeaderRequest() (v *UserHeaderRequest) {
	if !p.IsSetUserHeaderRequest() {
		return UserHeaderServiceQueryUserHeaderPageArgs_UserHeaderRequest_DEFAULT
	}
	return p.UserHeaderRequest
}
func (p *UserHeaderServiceQueryUserHeaderPageArgs) SetUserHeaderRequest(val *UserHeaderRequest) {
	p.UserHeaderRequest = val
}

func (p *UserHeaderServiceQueryUserHeaderPageArgs) IsSetUserHeaderRequest() bool {
	return p.UserHeaderRequest != nil
}

func (p *UserHeaderServiceQueryUserHeaderPageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderPageArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderPageArgs = map[int16]string{
	1: "userHeaderRequest",
}

type UserHeaderServiceQueryUserHeaderPageResult struct {
	Success *UserHeaderPageResponse `thrift:"success,0,optional" frugal:"0,optional,UserHeaderPageResponse" json:"success,omitempty"`
}

func NewUserHeaderServiceQueryUserHeaderPageResult() *UserHeaderServiceQueryUserHeaderPageResult {
	return &UserHeaderServiceQueryUserHeaderPageResult{}
}

func (p *UserHeaderServiceQueryUserHeaderPageResult) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderPageResult_Success_DEFAULT *UserHeaderPageResponse

func (p *UserHeaderServiceQueryUserHeaderPageResult) GetSuccess() (v *UserHeaderPageResponse) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceQueryUserHeaderPageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserHeaderServiceQueryUserHeaderPageResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserHeaderPageResponse)
}

func (p *UserHeaderServiceQueryUserHeaderPageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceQueryUserHeaderPageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderPageResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderPageResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceQueryUserHeaderListArgs struct {
	UserHeaderRequest *UserHeaderRequest `thrift:"userHeaderRequest,1" frugal:"1,default,UserHeaderRequest" json:"userHeaderRequest"`
}

func NewUserHeaderServiceQueryUserHeaderListArgs() *UserHeaderServiceQueryUserHeaderListArgs {
	return &UserHeaderServiceQueryUserHeaderListArgs{}
}

func (p *UserHeaderServiceQueryUserHeaderListArgs) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderListArgs_UserHeaderRequest_DEFAULT *UserHeaderRequest

func (p *UserHeaderServiceQueryUserHeaderListArgs) GetUserHeaderRequest() (v *UserHeaderRequest) {
	if !p.IsSetUserHeaderRequest() {
		return UserHeaderServiceQueryUserHeaderListArgs_UserHeaderRequest_DEFAULT
	}
	return p.UserHeaderRequest
}
func (p *UserHeaderServiceQueryUserHeaderListArgs) SetUserHeaderRequest(val *UserHeaderRequest) {
	p.UserHeaderRequest = val
}

func (p *UserHeaderServiceQueryUserHeaderListArgs) IsSetUserHeaderRequest() bool {
	return p.UserHeaderRequest != nil
}

func (p *UserHeaderServiceQueryUserHeaderListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderListArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderListArgs = map[int16]string{
	1: "userHeaderRequest",
}

type UserHeaderServiceQueryUserHeaderListResult struct {
	Success []*UserHeaderResponse `thrift:"success,0,optional" frugal:"0,optional,list<UserHeaderResponse>" json:"success,omitempty"`
}

func NewUserHeaderServiceQueryUserHeaderListResult() *UserHeaderServiceQueryUserHeaderListResult {
	return &UserHeaderServiceQueryUserHeaderListResult{}
}

func (p *UserHeaderServiceQueryUserHeaderListResult) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderListResult_Success_DEFAULT []*UserHeaderResponse

func (p *UserHeaderServiceQueryUserHeaderListResult) GetSuccess() (v []*UserHeaderResponse) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceQueryUserHeaderListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserHeaderServiceQueryUserHeaderListResult) SetSuccess(x interface{}) {
	p.Success = x.([]*UserHeaderResponse)
}

func (p *UserHeaderServiceQueryUserHeaderListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceQueryUserHeaderListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderListResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderListResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceQueryUserHeaderInfoArgs struct {
	UserHeaderRequest *UserHeaderRequest `thrift:"userHeaderRequest,1" frugal:"1,default,UserHeaderRequest" json:"userHeaderRequest"`
}

func NewUserHeaderServiceQueryUserHeaderInfoArgs() *UserHeaderServiceQueryUserHeaderInfoArgs {
	return &UserHeaderServiceQueryUserHeaderInfoArgs{}
}

func (p *UserHeaderServiceQueryUserHeaderInfoArgs) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderInfoArgs_UserHeaderRequest_DEFAULT *UserHeaderRequest

func (p *UserHeaderServiceQueryUserHeaderInfoArgs) GetUserHeaderRequest() (v *UserHeaderRequest) {
	if !p.IsSetUserHeaderRequest() {
		return UserHeaderServiceQueryUserHeaderInfoArgs_UserHeaderRequest_DEFAULT
	}
	return p.UserHeaderRequest
}
func (p *UserHeaderServiceQueryUserHeaderInfoArgs) SetUserHeaderRequest(val *UserHeaderRequest) {
	p.UserHeaderRequest = val
}

func (p *UserHeaderServiceQueryUserHeaderInfoArgs) IsSetUserHeaderRequest() bool {
	return p.UserHeaderRequest != nil
}

func (p *UserHeaderServiceQueryUserHeaderInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderInfoArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderInfoArgs = map[int16]string{
	1: "userHeaderRequest",
}

type UserHeaderServiceQueryUserHeaderInfoResult struct {
	Success *UserHeaderResponse `thrift:"success,0,optional" frugal:"0,optional,UserHeaderResponse" json:"success,omitempty"`
}

func NewUserHeaderServiceQueryUserHeaderInfoResult() *UserHeaderServiceQueryUserHeaderInfoResult {
	return &UserHeaderServiceQueryUserHeaderInfoResult{}
}

func (p *UserHeaderServiceQueryUserHeaderInfoResult) InitDefault() {
}

var UserHeaderServiceQueryUserHeaderInfoResult_Success_DEFAULT *UserHeaderResponse

func (p *UserHeaderServiceQueryUserHeaderInfoResult) GetSuccess() (v *UserHeaderResponse) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceQueryUserHeaderInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserHeaderServiceQueryUserHeaderInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserHeaderResponse)
}

func (p *UserHeaderServiceQueryUserHeaderInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceQueryUserHeaderInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserHeaderInfoResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserHeaderInfoResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceQueryUserPositionPageArgs struct {
	UserPositionRequest *user_position.UserPositionRequest `thrift:"userPositionRequest,1" frugal:"1,default,user_position.UserPositionRequest" json:"userPositionRequest"`
}

func NewUserHeaderServiceQueryUserPositionPageArgs() *UserHeaderServiceQueryUserPositionPageArgs {
	return &UserHeaderServiceQueryUserPositionPageArgs{}
}

func (p *UserHeaderServiceQueryUserPositionPageArgs) InitDefault() {
}

var UserHeaderServiceQueryUserPositionPageArgs_UserPositionRequest_DEFAULT *user_position.UserPositionRequest

func (p *UserHeaderServiceQueryUserPositionPageArgs) GetUserPositionRequest() (v *user_position.UserPositionRequest) {
	if !p.IsSetUserPositionRequest() {
		return UserHeaderServiceQueryUserPositionPageArgs_UserPositionRequest_DEFAULT
	}
	return p.UserPositionRequest
}
func (p *UserHeaderServiceQueryUserPositionPageArgs) SetUserPositionRequest(val *user_position.UserPositionRequest) {
	p.UserPositionRequest = val
}

func (p *UserHeaderServiceQueryUserPositionPageArgs) IsSetUserPositionRequest() bool {
	return p.UserPositionRequest != nil
}

func (p *UserHeaderServiceQueryUserPositionPageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserPositionPageArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserPositionPageArgs = map[int16]string{
	1: "userPositionRequest",
}

type UserHeaderServiceQueryUserPositionPageResult struct {
	Success *user_position.UserPositionPageResponse `thrift:"success,0,optional" frugal:"0,optional,user_position.UserPositionPageResponse" json:"success,omitempty"`
}

func NewUserHeaderServiceQueryUserPositionPageResult() *UserHeaderServiceQueryUserPositionPageResult {
	return &UserHeaderServiceQueryUserPositionPageResult{}
}

func (p *UserHeaderServiceQueryUserPositionPageResult) InitDefault() {
}

var UserHeaderServiceQueryUserPositionPageResult_Success_DEFAULT *user_position.UserPositionPageResponse

func (p *UserHeaderServiceQueryUserPositionPageResult) GetSuccess() (v *user_position.UserPositionPageResponse) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceQueryUserPositionPageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserHeaderServiceQueryUserPositionPageResult) SetSuccess(x interface{}) {
	p.Success = x.(*user_position.UserPositionPageResponse)
}

func (p *UserHeaderServiceQueryUserPositionPageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceQueryUserPositionPageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceQueryUserPositionPageResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceQueryUserPositionPageResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceSaveUserPositionArgs struct {
	UserPositionRequest *user_position.UserPositionRequest `thrift:"userPositionRequest,1" frugal:"1,default,user_position.UserPositionRequest" json:"userPositionRequest"`
}

func NewUserHeaderServiceSaveUserPositionArgs() *UserHeaderServiceSaveUserPositionArgs {
	return &UserHeaderServiceSaveUserPositionArgs{}
}

func (p *UserHeaderServiceSaveUserPositionArgs) InitDefault() {
}

var UserHeaderServiceSaveUserPositionArgs_UserPositionRequest_DEFAULT *user_position.UserPositionRequest

func (p *UserHeaderServiceSaveUserPositionArgs) GetUserPositionRequest() (v *user_position.UserPositionRequest) {
	if !p.IsSetUserPositionRequest() {
		return UserHeaderServiceSaveUserPositionArgs_UserPositionRequest_DEFAULT
	}
	return p.UserPositionRequest
}
func (p *UserHeaderServiceSaveUserPositionArgs) SetUserPositionRequest(val *user_position.UserPositionRequest) {
	p.UserPositionRequest = val
}

func (p *UserHeaderServiceSaveUserPositionArgs) IsSetUserPositionRequest() bool {
	return p.UserPositionRequest != nil
}

func (p *UserHeaderServiceSaveUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceSaveUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceSaveUserPositionArgs = map[int16]string{
	1: "userPositionRequest",
}

type UserHeaderServiceSaveUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserHeaderServiceSaveUserPositionResult() *UserHeaderServiceSaveUserPositionResult {
	return &UserHeaderServiceSaveUserPositionResult{}
}

func (p *UserHeaderServiceSaveUserPositionResult) InitDefault() {
}

var UserHeaderServiceSaveUserPositionResult_Success_DEFAULT bool

func (p *UserHeaderServiceSaveUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceSaveUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserHeaderServiceSaveUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserHeaderServiceSaveUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceSaveUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceSaveUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceSaveUserPositionResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceUpdateUserPositionArgs struct {
	UserPositionRequest *user_position.UserPositionRequest `thrift:"userPositionRequest,1" frugal:"1,default,user_position.UserPositionRequest" json:"userPositionRequest"`
}

func NewUserHeaderServiceUpdateUserPositionArgs() *UserHeaderServiceUpdateUserPositionArgs {
	return &UserHeaderServiceUpdateUserPositionArgs{}
}

func (p *UserHeaderServiceUpdateUserPositionArgs) InitDefault() {
}

var UserHeaderServiceUpdateUserPositionArgs_UserPositionRequest_DEFAULT *user_position.UserPositionRequest

func (p *UserHeaderServiceUpdateUserPositionArgs) GetUserPositionRequest() (v *user_position.UserPositionRequest) {
	if !p.IsSetUserPositionRequest() {
		return UserHeaderServiceUpdateUserPositionArgs_UserPositionRequest_DEFAULT
	}
	return p.UserPositionRequest
}
func (p *UserHeaderServiceUpdateUserPositionArgs) SetUserPositionRequest(val *user_position.UserPositionRequest) {
	p.UserPositionRequest = val
}

func (p *UserHeaderServiceUpdateUserPositionArgs) IsSetUserPositionRequest() bool {
	return p.UserPositionRequest != nil
}

func (p *UserHeaderServiceUpdateUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceUpdateUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceUpdateUserPositionArgs = map[int16]string{
	1: "userPositionRequest",
}

type UserHeaderServiceUpdateUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserHeaderServiceUpdateUserPositionResult() *UserHeaderServiceUpdateUserPositionResult {
	return &UserHeaderServiceUpdateUserPositionResult{}
}

func (p *UserHeaderServiceUpdateUserPositionResult) InitDefault() {
}

var UserHeaderServiceUpdateUserPositionResult_Success_DEFAULT bool

func (p *UserHeaderServiceUpdateUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceUpdateUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserHeaderServiceUpdateUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserHeaderServiceUpdateUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceUpdateUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceUpdateUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceUpdateUserPositionResult = map[int16]string{
	0: "success",
}

type UserHeaderServiceDeleteUserPositionArgs struct {
	UserPositionRequest *user_position.UserPositionRequest `thrift:"userPositionRequest,1" frugal:"1,default,user_position.UserPositionRequest" json:"userPositionRequest"`
}

func NewUserHeaderServiceDeleteUserPositionArgs() *UserHeaderServiceDeleteUserPositionArgs {
	return &UserHeaderServiceDeleteUserPositionArgs{}
}

func (p *UserHeaderServiceDeleteUserPositionArgs) InitDefault() {
}

var UserHeaderServiceDeleteUserPositionArgs_UserPositionRequest_DEFAULT *user_position.UserPositionRequest

func (p *UserHeaderServiceDeleteUserPositionArgs) GetUserPositionRequest() (v *user_position.UserPositionRequest) {
	if !p.IsSetUserPositionRequest() {
		return UserHeaderServiceDeleteUserPositionArgs_UserPositionRequest_DEFAULT
	}
	return p.UserPositionRequest
}
func (p *UserHeaderServiceDeleteUserPositionArgs) SetUserPositionRequest(val *user_position.UserPositionRequest) {
	p.UserPositionRequest = val
}

func (p *UserHeaderServiceDeleteUserPositionArgs) IsSetUserPositionRequest() bool {
	return p.UserPositionRequest != nil
}

func (p *UserHeaderServiceDeleteUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceDeleteUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceDeleteUserPositionArgs = map[int16]string{
	1: "userPositionRequest",
}

type UserHeaderServiceDeleteUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserHeaderServiceDeleteUserPositionResult() *UserHeaderServiceDeleteUserPositionResult {
	return &UserHeaderServiceDeleteUserPositionResult{}
}

func (p *UserHeaderServiceDeleteUserPositionResult) InitDefault() {
}

var UserHeaderServiceDeleteUserPositionResult_Success_DEFAULT bool

func (p *UserHeaderServiceDeleteUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserHeaderServiceDeleteUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserHeaderServiceDeleteUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserHeaderServiceDeleteUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserHeaderServiceDeleteUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderServiceDeleteUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserHeaderServiceDeleteUserPositionResult = map[int16]string{
	0: "success",
}
