// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/kouleen/user-center/kitex_gen/common"
)

type PageRequest struct {
	Current int64 `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size    int64 `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
}

func NewPageRequest() *PageRequest {
	return &PageRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *PageRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var PageRequest_Current_DEFAULT int64 = 1

func (p *PageRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return PageRequest_Current_DEFAULT
	}
	return p.Current
}

var PageRequest_Size_DEFAULT int64 = 10

func (p *PageRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return PageRequest_Size_DEFAULT
	}
	return p.Size
}
func (p *PageRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *PageRequest) SetSize(val int64) {
	p.Size = val
}

func (p *PageRequest) IsSetCurrent() bool {
	return p.Current != PageRequest_Current_DEFAULT
}

func (p *PageRequest) IsSetSize() bool {
	return p.Size != PageRequest_Size_DEFAULT
}

func (p *PageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequest(%+v)", *p)
}

var fieldIDToName_PageRequest = map[int16]string{
	1: "current",
	2: "size",
}

type UserHeaderRequest struct {
	UserIdList  []int64             `thrift:"userIdList,1,optional" frugal:"1,optional,list<i64>" json:"userIdList,omitempty"`
	Username    *string             `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Password    *string             `thrift:"password,3,optional" frugal:"3,optional,string" json:"password,omitempty"`
	Nickname    *string             `thrift:"nickname,4,optional" frugal:"4,optional,string" json:"nickname,omitempty"`
	Gender      *int32              `thrift:"gender,5,optional" frugal:"5,optional,i32" json:"gender,omitempty"`
	Avatar      *string             `thrift:"avatar,6,optional" frugal:"6,optional,string" json:"avatar,omitempty"`
	Phone       *string             `thrift:"phone,7,optional" frugal:"7,optional,string" json:"phone,omitempty"`
	Status      *int32              `thrift:"status,8,optional" frugal:"8,optional,i32" json:"status,omitempty"`
	PageRequest *PageRequest        `thrift:"PageRequest,9,optional" frugal:"9,optional,PageRequest" json:"PageRequest,omitempty"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255,optional" frugal:"255,optional,common.BaseRequest" json:"BaseRequest,omitempty"`
}

func NewUserHeaderRequest() *UserHeaderRequest {
	return &UserHeaderRequest{}
}

func (p *UserHeaderRequest) InitDefault() {
}

var UserHeaderRequest_UserIdList_DEFAULT []int64

func (p *UserHeaderRequest) GetUserIdList() (v []int64) {
	if !p.IsSetUserIdList() {
		return UserHeaderRequest_UserIdList_DEFAULT
	}
	return p.UserIdList
}

var UserHeaderRequest_Username_DEFAULT string

func (p *UserHeaderRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UserHeaderRequest_Username_DEFAULT
	}
	return *p.Username
}

var UserHeaderRequest_Password_DEFAULT string

func (p *UserHeaderRequest) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return UserHeaderRequest_Password_DEFAULT
	}
	return *p.Password
}

var UserHeaderRequest_Nickname_DEFAULT string

func (p *UserHeaderRequest) GetNickname() (v string) {
	if !p.IsSetNickname() {
		return UserHeaderRequest_Nickname_DEFAULT
	}
	return *p.Nickname
}

var UserHeaderRequest_Gender_DEFAULT int32

func (p *UserHeaderRequest) GetGender() (v int32) {
	if !p.IsSetGender() {
		return UserHeaderRequest_Gender_DEFAULT
	}
	return *p.Gender
}

var UserHeaderRequest_Avatar_DEFAULT string

func (p *UserHeaderRequest) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UserHeaderRequest_Avatar_DEFAULT
	}
	return *p.Avatar
}

var UserHeaderRequest_Phone_DEFAULT string

func (p *UserHeaderRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UserHeaderRequest_Phone_DEFAULT
	}
	return *p.Phone
}

var UserHeaderRequest_Status_DEFAULT int32

func (p *UserHeaderRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return UserHeaderRequest_Status_DEFAULT
	}
	return *p.Status
}

var UserHeaderRequest_PageRequest_DEFAULT *PageRequest

func (p *UserHeaderRequest) GetPageRequest() (v *PageRequest) {
	if !p.IsSetPageRequest() {
		return UserHeaderRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var UserHeaderRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *UserHeaderRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return UserHeaderRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *UserHeaderRequest) SetUserIdList(val []int64) {
	p.UserIdList = val
}
func (p *UserHeaderRequest) SetUsername(val *string) {
	p.Username = val
}
func (p *UserHeaderRequest) SetPassword(val *string) {
	p.Password = val
}
func (p *UserHeaderRequest) SetNickname(val *string) {
	p.Nickname = val
}
func (p *UserHeaderRequest) SetGender(val *int32) {
	p.Gender = val
}
func (p *UserHeaderRequest) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *UserHeaderRequest) SetPhone(val *string) {
	p.Phone = val
}
func (p *UserHeaderRequest) SetStatus(val *int32) {
	p.Status = val
}
func (p *UserHeaderRequest) SetPageRequest(val *PageRequest) {
	p.PageRequest = val
}
func (p *UserHeaderRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *UserHeaderRequest) IsSetUserIdList() bool {
	return p.UserIdList != nil
}

func (p *UserHeaderRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UserHeaderRequest) IsSetPassword() bool {
	return p.Password != nil
}

func (p *UserHeaderRequest) IsSetNickname() bool {
	return p.Nickname != nil
}

func (p *UserHeaderRequest) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UserHeaderRequest) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UserHeaderRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UserHeaderRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UserHeaderRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *UserHeaderRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *UserHeaderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderRequest(%+v)", *p)
}

var fieldIDToName_UserHeaderRequest = map[int16]string{
	1:   "userIdList",
	2:   "username",
	3:   "password",
	4:   "nickname",
	5:   "gender",
	6:   "avatar",
	7:   "phone",
	8:   "status",
	9:   "PageRequest",
	255: "BaseRequest",
}

type UserHeaderResponse struct {
	Username     string               `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password     string               `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Nickname     string               `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
	Gender       int32                `thrift:"gender,4,required" frugal:"4,required,i32" json:"gender"`
	Avatar       string               `thrift:"avatar,5" frugal:"5,default,string" json:"avatar"`
	Phone        string               `thrift:"phone,6" frugal:"6,default,string" json:"phone"`
	Status       int32                `thrift:"status,7,required" frugal:"7,required,i32" json:"status"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewUserHeaderResponse() *UserHeaderResponse {
	return &UserHeaderResponse{}
}

func (p *UserHeaderResponse) InitDefault() {
}

func (p *UserHeaderResponse) GetUsername() (v string) {
	return p.Username
}

func (p *UserHeaderResponse) GetPassword() (v string) {
	return p.Password
}

func (p *UserHeaderResponse) GetNickname() (v string) {
	return p.Nickname
}

func (p *UserHeaderResponse) GetGender() (v int32) {
	return p.Gender
}

func (p *UserHeaderResponse) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserHeaderResponse) GetPhone() (v string) {
	return p.Phone
}

func (p *UserHeaderResponse) GetStatus() (v int32) {
	return p.Status
}

var UserHeaderResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *UserHeaderResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return UserHeaderResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *UserHeaderResponse) SetUsername(val string) {
	p.Username = val
}
func (p *UserHeaderResponse) SetPassword(val string) {
	p.Password = val
}
func (p *UserHeaderResponse) SetNickname(val string) {
	p.Nickname = val
}
func (p *UserHeaderResponse) SetGender(val int32) {
	p.Gender = val
}
func (p *UserHeaderResponse) SetAvatar(val string) {
	p.Avatar = val
}
func (p *UserHeaderResponse) SetPhone(val string) {
	p.Phone = val
}
func (p *UserHeaderResponse) SetStatus(val int32) {
	p.Status = val
}
func (p *UserHeaderResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *UserHeaderResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *UserHeaderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderResponse(%+v)", *p)
}

var fieldIDToName_UserHeaderResponse = map[int16]string{
	1:   "username",
	2:   "password",
	3:   "nickname",
	4:   "gender",
	5:   "avatar",
	6:   "phone",
	7:   "status",
	255: "BaseResponse",
}

type UserHeaderPageResponse struct {
	Total   int64                 `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*UserHeaderResponse `thrift:"records,2,required" frugal:"2,required,list<UserHeaderResponse>" json:"records"`
}

func NewUserHeaderPageResponse() *UserHeaderPageResponse {
	return &UserHeaderPageResponse{}
}

func (p *UserHeaderPageResponse) InitDefault() {
}

func (p *UserHeaderPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *UserHeaderPageResponse) GetRecords() (v []*UserHeaderResponse) {
	return p.Records
}
func (p *UserHeaderPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *UserHeaderPageResponse) SetRecords(val []*UserHeaderResponse) {
	p.Records = val
}

func (p *UserHeaderPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserHeaderPageResponse(%+v)", *p)
}

var fieldIDToName_UserHeaderPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
