// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"fmt"
)

type LoginRequest struct {
	Username  string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Phone     string `thrift:"phone,2" frugal:"2,default,string" json:"phone"`
	Code      string `thrift:"code,3" frugal:"3,default,string" json:"code"`
	Password  string `thrift:"password,4" frugal:"4,default,string" json:"password"`
	LoginType *int32 `thrift:"loginType,5,optional" frugal:"5,optional,i32" json:"loginType,omitempty"`
	Uuid      string `thrift:"uuid,6" frugal:"6,default,string" json:"uuid"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPhone() (v string) {
	return p.Phone
}

func (p *LoginRequest) GetCode() (v string) {
	return p.Code
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}

var LoginRequest_LoginType_DEFAULT int32

func (p *LoginRequest) GetLoginType() (v int32) {
	if !p.IsSetLoginType() {
		return LoginRequest_LoginType_DEFAULT
	}
	return *p.LoginType
}

func (p *LoginRequest) GetUuid() (v string) {
	return p.Uuid
}
func (p *LoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *LoginRequest) SetPhone(val string) {
	p.Phone = val
}
func (p *LoginRequest) SetCode(val string) {
	p.Code = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}
func (p *LoginRequest) SetLoginType(val *int32) {
	p.LoginType = val
}
func (p *LoginRequest) SetUuid(val string) {
	p.Uuid = val
}

func (p *LoginRequest) IsSetLoginType() bool {
	return p.LoginType != nil
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "username",
	2: "phone",
	3: "code",
	4: "password",
	5: "loginType",
	6: "uuid",
}

type LoginResponse struct {
	AccessToken string `thrift:"accessToken,1" frugal:"1,default,string" json:"accessToken"`
	ExpireTime  *int64 `thrift:"expireTime,2,optional" frugal:"2,optional,i64" json:"expireTime,omitempty"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

func (p *LoginResponse) GetAccessToken() (v string) {
	return p.AccessToken
}

var LoginResponse_ExpireTime_DEFAULT int64

func (p *LoginResponse) GetExpireTime() (v int64) {
	if !p.IsSetExpireTime() {
		return LoginResponse_ExpireTime_DEFAULT
	}
	return *p.ExpireTime
}
func (p *LoginResponse) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *LoginResponse) SetExpireTime(val *int64) {
	p.ExpireTime = val
}

func (p *LoginResponse) IsSetExpireTime() bool {
	return p.ExpireTime != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "accessToken",
	2: "expireTime",
}
